//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZakazBar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public int if_dish { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
