//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZakazBar
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        public int ID { get; set; }
        public string item { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
